name: "Setup test environment"
description: ""
inputs: {}
outputs: {}
runs:
  using: "composite"
  steps:
    - uses: cachix/install-nix-action@v18
      with:
        install_url: https://releases.nixos.org/nix/nix-2.11.1/install
    - run: nix flake check
      shell: bash
    - name: Add Gadget npm registry
      shell: nix develop -c bash -eo pipefail -l {0}
      run: npm config set @gadget-client:registry https://registry.gadget.dev/npm
    - name: Install dependencies with pnpm
      shell: nix develop -c bash -eo pipefail -l {0}
      run: pnpm install
