name: Release
on:
  push:
    branches:
      - main
    paths:
      - 'packages/**/package.json'
jobs:
  test:
    uses: ./.github/workflows/test.yml
  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: ./.github/actions/setup-test-env
      - name: Build all packages
        shell: nix develop -c bash -eo pipefail -l {0}
        run: yarn build
      - name: Publish @gadgetinc/api-client-core
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./packages/api-client-core/package.json
          access: public
      - name: Publish @gadgetinc/react
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./packages/react/package.json
          access: public
