name: "Test"
on:
  push:
  workflow_call:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-test-env
      - name: Build all packages (so they can require each other)
        shell: nix develop -c bash -eo pipefail -l {0}
        run: yarn build
      - name: Test
        shell: nix develop -c bash -eo pipefail -l {0}
        run: yarn test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-test-env
      - name: Build all packages (so they can require each other)
        shell: nix develop -c bash -eo pipefail -l {0}
        run: yarn build
      - name: Lint
        shell: nix develop -c bash -eo pipefail -l {0}
        run: yarn lint
  versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-test-env
      - name: Check dependency versions
        shell: nix develop -c bash -eo pipefail -l {0}
        run: yarn check-dependency-versions
