name: "Test"
on:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v14
      with:
        install_url: https://nixos-nix-install-tests.cachix.org/serve/vij683ly7sl95nnhb67bdjjfabclr85m/install
        install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - run: nix flake check
    - name: Install dependencies with yarn install
      shell: nix develop -c bash -eo pipefail -l {0}
      run: |
        yarn install
    - name: Lint
      shell: nix develop -c bash -eo pipefail -l {0}
      run: |
        yarn lint
    - name: Test
      shell: nix develop -c bash -eo pipefail -l {0}
      run: |
        yarn test